app:
    resource: '@AppBundle/Controller/'
    type: annotation

products:
    type:     rest
    resource: AppBundle\Controller\ProductController

categories:
    type:     rest
    resource: AppBundle\Controller\CategoryController

brands:
    type:     rest
    resource: AppBundle\Controller\BrandController